import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Image from "next/image";
import leftBgElement from "../public/assets/001.svg";
import rightBgElement from "../public/assets/002.svg";
import rightBgBallElement from "../public/assets/blobanimation.svg";
export default ({ children }) => {
  return (
    <>
      <Head>
        <title>Bike FixUp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-slate-300 w-full h-screen overflow-hidden">
       <div className="p-2 sm:p-5 md:p-10 h-full overflow-y-scroll">
          <div className="max-w-7xl mx-auto backdrop-filter bg-clip-padding backdrop-blur-2xl bg-opacity-50 border border-white rounded-3xl overflow-hidden w-full text-slate-200 relative">
            <Image
              className="absolute top-[150px] w-[290px] -z-10"
              src={leftBgElement}
              alt="element"
              priority
            />
            <Image
              className="absolute top-[190px] right-0 w-[250px] -z-10"
              src={rightBgBallElement}
              alt="element"
              priority
            />
            <Image
              className="absolute top-[150px] right-0 w-[200px] -z-10"
              src={rightBgElement}
              alt="element"
              priority
            />
            <Header />
            <main className="px-3 md:px-14 lg:px-24">{children}</main>
            <Footer />
          </div>
       </div>
      </div>
    </>
  );
};
